### PR TITLE
Content types

### PR DESCRIPTION
**Pull request by ryanfiller**
This PR very quick-and-dirty:
 - adds content types for `news`, `resources`, and `closures`
 - adds list pages for `news`, `resources`, and `closures`
 - adds preview sections to the homepage for `news`, `resources`, and `closures` if they have any content items
- adds a few components needed to build out pages, `posts`, `markdown`, etc...
- moves some content

*TODO*
- I did my best to port content to the appropriate places, I'm sure I didn't get it all. Anyone can manually go in and add more things in the appreciate places in the content folder, next on my list is to tweak NetlifyCMS to get this community editable.
- Someone should probably take a styling pass at this, I didn't really add any new styles and some of the hierarchy could be improved so people can find information better.

### CODE REVIEW

**Comment by ryanfiller** [comment]
Also, I can make time to explain any of this. A lot of it I copy/pasted from my blog just to get a lot of the boilerpolate out of the way. Sorry for the massive PR, I know you mentioned you were new to programming/Gatsby.

**Comment by tidymemphis** [comment]
Awesome! I finally figured out how to check out your branch (did I mention I'm new to git too lol) and it looks great! I'm making a few changes--mostly just putting all the service industry resources into one page. Ideally each industry that's affected can have a page with resources specific to them.

**Comment by ryanfiller** [comment]
Uh oh, it looks like there's some conflicts here as well. I think you made some changes after I forked, I can see if I can rebase this up to date so nobody has to manually resolve the conflicts.

I've been using git for a while, but this will be my first time trying to rebase across forks, so we'll all learn something today.

**Comment by tidymemphis** [comment]
don't worry about it, I already fixed it on my end and I'm about to post my changes. I had just added some emojis and I figured out how to fix it.

**Comment by ryanfiller** [comment]
I think we should be good to go on this? I fixed all the conflicts and made the changes you requested.

**Pull request merged**
